Models/Promotion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TracyShop.Models
{
    public class Promotion
    {
        [Key]
        public int Id { set; get; }
        public float percent { set; get; }
        public DateTime StartedDate { set; get; }
        public DateTime EndDate { set; get; }

        public virtual ICollection<Product> Products { set; get; }
    }
}

Areas/Admin/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TracyShop.Data;
using TracyShop.Models;

namespace TracyShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PromotionsController : Controller
    {
        private readonly AppDbContext _context;

        public PromotionsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Promotions
        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Promotion.ToListAsync());
        }


        // GET: Admin/Promotions/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Promotions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,percent,StartedDate,EndDate")] Promotion promotion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(promotion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(promotion);
        }

        // GET: Admin/Promotions/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion.FindAsync(id);
            if (promotion == null)
            {
                return NotFound();
            }
            return View(promotion);
        }

        // POST: Admin/Promotions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,percent,StartedDate,EndDate")] Promotion promotion)
        {
            if (id != promotion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promotion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromotionExists(promotion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(promotion);
        }

        // POST: Admin/Promotions/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var promotion = await _context.Promotion.FindAsync(id);
            _context.Promotion.Remove(promotion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PromotionExists(int id)
        {
            return _context.Promotion.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Views/Promotions/Create.cshtml
@model TracyShop.Models.Promotion

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thêm ưu đãi</h1>
    <a asp-area="Admin" asp-controller="Promotions" asp-action="Index" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-arrow-alt-circle-left text-white-50"></i> Quay lại
    </a>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="percent" class="control-label">Mức giảm giá</label>
                <input asp-for="percent" class="form-control" />
                <span asp-validation-for="percent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartedDate" class="control-label">Ngày bắt đầu</label>
                <input asp-for="StartedDate" class="form-control" type="date" />
                <span asp-validation-for="StartedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Ngày kết thúc</label>
                <input asp-for="EndDate" class="form-control" type="date" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm ưu đãi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Areas/Admin/Views/Promotions/Edit.cshtml
@model TracyShop.Models.Promotion

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Chỉnh sửa ưu đãi</h1>
    <a asp-area="Admin" asp-controller="Promotions" asp-action="Index" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-arrow-alt-circle-left text-white-50"></i> Quay lại
    </a>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="percent" class="control-label">Mức giảm giá</label>
                <input asp-for="percent" class="form-control" />
                <span asp-validation-for="percent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartedDate" class="control-label">Ngày bắt đầu</label>
                <input asp-for="StartedDate" class="form-control" type="date" />
                <span asp-validation-for="StartedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Ngày bắt đầu</label>
                <input asp-for="EndDate" class="form-control" type="date" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Areas/Admin/Views/Promotions/Index.cshtml
@model IEnumerable<TracyShop.Models.Promotion>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@inject TracyShop.Data.AppDbContext _context

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Danh sách ưu đãi</h1>

    @if (_context.UserRoles.Where(r => r.UserId.Contains(User.FindFirst("Id").Value)).First().RoleId == "1")
    {
        <a asp-area="Admin" asp-controller="Promotions" asp-action="Create" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus-circle text-white-50"></i> Thêm ưu đãi
        </a>
    }

</div>
<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Mức giảm giá
            </th>
            <th>
                Ngày bắt đầu
            </th>
            <th>
                Ngày kết thúc
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.percent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                @if (_context.UserRoles.Where(r => r.UserId.Contains(User.FindFirst("Id").Value)).First().RoleId == "1")
                {
                    <td>
                        <a asp-area="Admin" asp-controller="Promotions" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a> |
                        <button data-id="@item.Id" class="btn deletePromotion" type="button"> <i class="far fa-trash-alt"></i></button> |
                    </td>
                }
                else
                {
                    <td></td>
                }

            </tr>
        }
    </tbody>
</table>

<form id="deletePromotion" asp-action="Delete">
    <input type="hidden" id="promotionId" name="Id" />
</form>

@section Scripts{
    <script>
        $(function(){
            $('.deletePromotion').click(function(e) {
                swal({
                    title: "Bạn chắc chắn?",
                    text: "Bạn chắc chắn muốn xóa chương trình khuyến mãi này?",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true
                }).then((confirm) => {
                        if(confirm){
                            var btn = $(this);
                            var id = btn.data("id");
                            $('#promotionId').val(id);
                            $('#deletePromotion').submit();
                        }
                    });
            });
        });
    </script>
}