ViewModels/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TracyShop.ViewModels
{
    public class ReportViewModel
    {
        public float Revenue { set; get; }  // doanh thu
        public float Profit { set; get; }   // lợi nhuận
        public float CostPrice { set; get; }    // giá vốn
        public int SelectedMonth { set; get; }
        public int SelectedYear { set; get; }
        public List<int> Months { set; get; }
        public List<int> Years { set; get; }
        public List<float> ProfitList { set; get; } // Lợi nhuận của các tháng trong năm
        public List<float> RevenueList { set; get; }    // Doanh thu của các tháng trong năm
    }
}

Areas/Admin/Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using TracyShop.Data;
using TracyShop.ViewModels;

namespace TracyShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ReportController : Controller
    {
        private readonly AppDbContext _context;

        public ReportController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        [Route("/admin/report-by-month", Name ="report-by-month")]
        public IActionResult ReportByMonth()
        {
            var report = new ReportViewModel();
            DateTime now = DateTime.Now;

            // Hiển thị lên giao diện
            report.Months = new List<int>();
            for (int i = 1; i <= 12; i++)
            {
                report.Months.Add(i);
            }
            report.Years = new List<int>();
            for(int i = 1970; i <= now.Year; i++)
            {
                report.Years.Add(i);
            }
            report.SelectedMonth = now.Month;
            report.SelectedYear = now.Year;

            // Tính doanh thu

            report.Revenue = RevenueByMonth(now.Month, now.Year);

            // Tính giá vốn

            report.CostPrice = CostPriceByMonth(now.Month, now.Year);

            // Tính lợi nhuận
            report.Profit = report.Revenue - report.CostPrice;

            return View(report);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [Route("/admin/report-by-month", Name = "report-by-month")]
        public IActionResult ReportByMonth(ReportViewModel reportView)
        {
            var report = new ReportViewModel();

            // Hiển thị lên giao diện
            report.Months = new List<int>();
            for (int i = 1; i <= 12; i++)
            {
                report.Months.Add(i);
            }
            report.Years = new List<int>();
            for (int i = 1970; i <= DateTime.Now.Year; i++)
            {
                report.Years.Add(i);
            }
            report.SelectedMonth = reportView.SelectedMonth;
            report.SelectedYear = reportView.SelectedYear;

            // Tính doanh thu

            report.Revenue = RevenueByMonth(reportView.SelectedMonth, reportView.SelectedYear);

            // Tính giá vốn

            report.CostPrice = CostPriceByMonth(report.SelectedMonth, report.SelectedYear);

            // Tính lợi nhuận
            report.Profit = (report.Revenue - report.CostPrice);

            return View(report);
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        [Route("/admin/report-by-year", Name = "report-by-year")]
        public IActionResult ReportByYear()
        {
            var report = new ReportViewModel();
            DateTime now = DateTime.Now;

            // Hiển thị lên giao diện
            report.Years = new List<int>();
            for (int i = 1970; i <= now.Year; i++)
            {
                report.Years.Add(i);
            }
            report.SelectedYear = now.Year;

            // Lợi nhuận và doanh thu của các tháng trong năm
            report.ProfitList = new List<float>();
            report.RevenueList = new List<float>();

            for(int i = 1; i <= 12; i++)
            {
                // Doanh thu tháng thứ i

                var revenue = RevenueByMonth(i, now.Year);

                // Vốn tháng thứ i

                var costPrice = CostPriceByMonth(i, now.Year);

                // Lợi nhuận tháng thứ i
                var profit = revenue - costPrice;
                report.ProfitList.Add(profit);

                // Doanh thu tháng thứ i
                report.RevenueList.Add(revenue);
            }

            // Tính doanh thu

            report.Revenue = RevenueByMonth(0, now.Year);

            // Tính giá vốn

            report.CostPrice = CostPriceByMonth(0, now.Year);

            // Tính lợi nhuận
            report.Profit = report.Revenue - report.CostPrice;

            return View(report);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [Route("/admin/report-by-year", Name = "report-by-year")]
        public IActionResult ReportByYear(ReportViewModel reportView)
        {
            var report = new ReportViewModel();

            // Hiển thị lên giao diện
            report.Years = new List<int>();
            for (int i = 1970; i <= DateTime.Now.Year; i++)
            {
                report.Years.Add(i);
            }
            report.SelectedYear = reportView.SelectedYear;

            // Lợi nhuận và doanh thu của các tháng trong năm
            report.ProfitList = new List<float>();
            report.RevenueList = new List<float>();
            for (int i = 1; i <= 12; i++)
            {
                // Doanh thu tháng thứ i

                var revenue = RevenueByMonth(i, reportView.SelectedYear);

                // Vốn tháng thứ i

                var costPrice = CostPriceByMonth(i, reportView.SelectedYear);

                // Lợi nhuận tháng thứ i
                var profit = revenue - costPrice;
                report.ProfitList.Add(profit);

                // Doanh thu tháng thứ i
                report.RevenueList.Add(revenue);
            }

            // Tính doanh thu

            report.Revenue = RevenueByMonth(0, reportView.SelectedYear);

            // Tính giá vốn

            report.CostPrice = CostPriceByMonth(0, report.SelectedYear);

            // Tính lợi nhuận
            report.Profit = (report.Revenue - report.CostPrice);

            return View(report);
        }

#region Helper

        private float RevenueByMonth(int month, int year)
        {
            var orders = month > 0 ? _context.Orders.Where(o => o.Created_date.Month == month && o.Created_date.Year == year && (o.Status < 4 && o.Status > 0)).ToList()
                                    : _context.Orders.Where(o => o.Created_date.Year == year && (o.Status < 4 && o.Status > 0)).ToList();
            float revenue = 0;
            foreach (var item in orders)
            {
                var orderdetails = _context.OrderDetail.Where(d => d.OrderId == item.Id).ToList();
                foreach (var i in orderdetails)
                {
                    var price = _context.OrderDetail.Where(d => d.Id == i.Id).First();
                    revenue += price.Price * price.Quantity;
                }
            }
            return revenue;
        }

        private float CostPriceByMonth(int month, int year)
        {
            var stocks = month > 0 ? _context.StockReceived.Where(s => s.Date.Month == month && s.Date.Year == year).ToList()
                                    : _context.StockReceived.Where(s => s.Date.Year == year).ToList();
            float costPrice = 0;
            foreach (var item in stocks)
            {
                var stockdetails = _context.StockReceivedDetail.Where(s => s.StockReceivedId == item.Id).ToList();
                foreach (var temp in stockdetails)
                {
                    var detail = _context.StockReceivedDetail.Where(r => r.Id == temp.Id).First();
                    costPrice += detail.Unit_price * detail.Quantity;
                }
            }
            return costPrice;
        }

#endregion
    }
}

Areas/Admin/Views/Report/ReportByMonth.cshtml
@model TracyShop.ViewModels.ReportViewModel
@{
    ViewData["Title"] = "Report By Month";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thống kê theo tháng</h1>
</div>
<form asp-action="ReportByMonth" asp-controller="Report" asp-area="Admin">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="SelectedMonth" class="control-label">Chọn tháng</label>
                <select asp-for="SelectedMonth" asp-items="@(new SelectList(Model.Months))" class="form-control">
                    <option value="0">Chọn tháng</option>
                </select>
                <span asp-validation-for="SelectedMonth" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="SelectedYear" class="control-label">Chọn năm</label>
                <select asp-for="SelectedYear" asp-items="@(new SelectList(Model.Years))" class="form-control">
                    <option value="0">Chọn năm</option>
                </select>
                <span asp-validation-for="SelectedYear" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group" style="margin-top: 7px;">
                <br />
                <input type="submit" value="Chọn" class="btn btn-primary" />
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Tháng</th>
                <th>Doanh thu</th>
                <th>Vốn</th>
                <th>Lợi nhuận</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.SelectedMonth/@Model.SelectedYear</td>
                <td>@String.Format("{0:0,0}", Model.Revenue) VNĐ</td>
                <td>@String.Format("{0:0,0}", Model.CostPrice) VNĐ</td>
                <td>@String.Format("{0:0,0}", Model.Profit) VNĐ</td>
            </tr>
        </tbody>
    </table>
    <!-- Pie Chart -->
    <div class="col-xl-6 col-lg-7 container">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Biểu đồ thống kê tháng @Model.SelectedMonth/@Model.SelectedYear</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-pie pt-4 pb-2">
                    <canvas id="myPieChart"></canvas>
                </div>
                <div class="mt-4 text-center small">
                    <span class="mr-2">
                        <i class="fas fa-circle text-primary"></i> Doanh thu
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-success"></i> Lợi nhuận
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-info"></i> Vốn
                    </span>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{ 
    <script>
        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#858796';

        // Pie Chart Example
        var ctx = document.getElementById("myPieChart");
        var myPieChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: ["Doanh thu", "Lợi nhuận", "Vốn"],
                datasets: [{
                    data: [@Model.Revenue, @Model.Profit, @Model.CostPrice],
                    backgroundColor: ['#4e73df', '#1cc88a', '#36b9cc'],
                    hoverBackgroundColor: ['#2e59d9', '#17a673', '#2c9faf'],
                    hoverBorderColor: "rgba(234, 236, 244, 1)",
                }],
            },
            options: {
                maintainAspectRatio: false,
                tooltips: {
                    backgroundColor: "rgb(255,255,255)",
                    bodyFontColor: "#858796",
                    borderColor: '#dddfeb',
                    borderWidth: 1,
                    xPadding: 15,
                    yPadding: 15,
                    displayColors: false,
                    caretPadding: 10,
                },
                legend: {
                    display: false
                },
                cutoutPercentage: 80,
            },
        });
    </script>

}

Areas/Admin/Views/Report/ReportByYear.cshtml
@model TracyShop.ViewModels.ReportViewModel
@{
    ViewData["Title"] = "Report By Year";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thống kê theo năm</h1>
</div>
<form asp-action="ReportByYear" asp-controller="Report" asp-area="Admin">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="SelectedYear" class="control-label">Chọn năm</label>
                <select asp-for="SelectedYear" asp-items="@(new SelectList(Model.Years))" class="form-control">
                    <option value="0">Chọn năm</option>
                </select>
                <span asp-validation-for="SelectedYear" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group" style="margin-top: 7px;">
                <br />
                <input type="submit" value="Chọn" class="btn btn-primary" />
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Năm</th>
                <th>Doanh thu</th>
                <th>Vốn</th>
                <th>Lợi nhuận</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.SelectedYear</td>
                <td>@String.Format("{0:0,0}", Model.Revenue) VNĐ</td>
                <td>@String.Format("{0:0,0}", Model.CostPrice) VNĐ</td>
                <td>@String.Format("{0:0,0}", Model.Profit) VNĐ</td>
            </tr>
        </tbody>
    </table>

    <!--Biểu đồ thống kê doanh thu của tháng trong năm-->
    <!-- Bar Chart -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Biểu đồ thống kê doanh thu của các tháng trong năm @Model.SelectedYear</h6>
        </div>
        <div class="card-body">
            <div class="chart-bar">
                <canvas id="myBarChart"></canvas>
            </div>
        </div>
    </div>

    <!--Biểu đồ thống kê lợi nhuận của các tháng trong năm-->
    <!-- Area Chart -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Biểu đồ thống kê lợi nhuận của các tháng trong năm @Model.SelectedYear</h6>
        </div>
        <div class="card-body">
            <div class="chart-area">
                <canvas id="myAreaChart"></canvas>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    <!--Biểu đồ cột-->
    <script>
        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#858796';

        function number_format(number, decimals, dec_point, thousands_sep) {
            // *     example: number_format(1234.56, 2, ',', ' ');
            // *     return: '1 234,56'
            number = (number + '').replace(',', '').replace(' ', '');
            var n = !isFinite(+number) ? 0 : +number,
                prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
                sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
                dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
                s = '',
                toFixedFix = function (n, prec) {
                    var k = Math.pow(10, prec);
                    return '' + Math.round(n * k) / k;
                };
            // Fix for IE parseFloat(0.55).toFixed(0) = 0;
            s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
            if (s[0].length > 3) {
                s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
            }
            if ((s[1] || '').length < prec) {
                s[1] = s[1] || '';
                s[1] += new Array(prec - s[1].length + 1).join('0');
            }
            return s.join(dec);
        }

        // Bar Chart Example
        var ctx = document.getElementById("myBarChart");
        var myBarChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
                datasets: [{
                    label: "Doanh thu",
                    backgroundColor: "#4e73df",
                    hoverBackgroundColor: "#2e59d9",
                    borderColor: "#4e73df",
                    data: [
                        @Model.RevenueList[0], @Model.RevenueList[1], @Model.RevenueList[2], @Model.RevenueList[3], @Model.RevenueList[4], @Model.RevenueList[5],
                        @Model.RevenueList[6], @Model.RevenueList[7], @Model.RevenueList[8], @Model.RevenueList[9], @Model.RevenueList[10], @Model.RevenueList[11]
                    ],
                }],
            },
            options: {
                maintainAspectRatio: false,
                layout: {
                    padding: {
                        left: 10,
                        right: 25,
                        top: 25,
                        bottom: 0
                    }
                },
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'tháng'
                        },
                        gridLines: {
                            display: false,
                            drawBorder: false
                        },
                        ticks: {
                            maxTicksLimit: 12
                        },
                        maxBarThickness: 25,
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: 20000000,
                            maxTicksLimit: 5,
                            padding: 10,
                            // Include a dollar sign in the ticks
                            callback: function (value, index, values) {
                                return '$' + number_format(value);
                            }
                        },
                        gridLines: {
                            color: "rgb(234, 236, 244)",
                            zeroLineColor: "rgb(234, 236, 244)",
                            drawBorder: false,
                            borderDash: [1],
                            zeroLineBorderDash: [1]
                        }
                    }],
                },
                legend: {
                    display: false
                },
                tooltips: {
                    titleMarginBottom: 10,
                    titleFontColor: '#6e707e',
                    titleFontSize: 14,
                    backgroundColor: "rgb(255,255,255)",
                    bodyFontColor: "#858796",
                    borderColor: '#dddfeb',
                    borderWidth: 1,
                    xPadding: 15,
                    yPadding: 15,
                    displayColors: false,
                    caretPadding: 10,
                    callbacks: {
                        label: function (tooltipItem, chart) {
                            var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
                            return datasetLabel + ': $' + number_format(tooltipItem.yLabel);
                        }
                    }
                },
            }
        });
    </script>

    <!--Biểu đồ đường-->
    <script>
        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#858796';

        function number_format(number, decimals, dec_point, thousands_sep) {
            // *     example: number_format(1234.56, 2, ',', ' ');
            // *     return: '1 234,56'
            number = (number + '').replace(',', '').replace(' ', '');
            var n = !isFinite(+number) ? 0 : +number,
                prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
                sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
                dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
                s = '',
                toFixedFix = function (n, prec) {
                    var k = Math.pow(10, prec);
                    return '' + Math.round(n * k) / k;
                };
            // Fix for IE parseFloat(0.55).toFixed(0) = 0;
            s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
            if (s[0].length > 3) {
                s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
            }
            if ((s[1] || '').length < prec) {
                s[1] = s[1] || '';
                s[1] += new Array(prec - s[1].length + 1).join('0');
            }
            return s.join(dec);
        }

        // Area Chart Example
        var ctx = document.getElementById("myAreaChart");
        var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
                datasets: [{
                    label: "Lợi nhuận",
                    lineTension: 0.3,
                    backgroundColor: "rgba(78, 115, 223, 0.05)",
                    borderColor: "rgba(78, 115, 223, 1)",
                    pointRadius: 3,
                    pointBackgroundColor: "rgba(78, 115, 223, 1)",
                    pointBorderColor: "rgba(78, 115, 223, 1)",
                    pointHoverRadius: 3,
                    pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
                    pointHoverBorderColor: "rgba(78, 115, 223, 1)",
                    pointHitRadius: 10,
                    pointBorderWidth: 2,
                    data: [
                        @Model.ProfitList[0], @Model.ProfitList[1], @Model.ProfitList[2], @Model.ProfitList[3], @Model.ProfitList[4], @Model.ProfitList[5],
                        @Model.ProfitList[6], @Model.ProfitList[7], @Model.ProfitList[8], @Model.ProfitList[9], @Model.ProfitList[10], @Model.ProfitList[11]
                    ],
                }],
            },
            options: {
                maintainAspectRatio: false,
                layout: {
                    padding: {
                        left: 10,
                        right: 25,
                        top: 25,
                        bottom: 0
                    }
                },
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'ngày'
                        },
                        gridLines: {
                            display: false,
                            drawBorder: false
                        },
                        ticks: {
                            maxTicksLimit: 12
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: 4000000,
                            maxTicksLimit: 5,
                            padding: 10,
                            // Include a dollar sign in the ticks
                            callback: function (value, index, values) {
                                return '$' + number_format(value);
                            }
                        },
                        gridLines: {
                            color: "rgb(234, 236, 244)",
                            zeroLineColor: "rgb(234, 236, 244)",
                            drawBorder: false,
                            borderDash: [1],
                            zeroLineBorderDash: [1]
                        }
                    }],
                },
                legend: {
                    display: false
                },
                tooltips: {
                    backgroundColor: "rgb(255,255,255)",
                    bodyFontColor: "#858796",
                    titleMarginBottom: 10,
                    titleFontColor: '#6e707e',
                    titleFontSize: 14,
                    borderColor: '#dddfeb',
                    borderWidth: 1,
                    xPadding: 15,
                    yPadding: 15,
                    displayColors: false,
                    intersect: false,
                    mode: 'index',
                    caretPadding: 10,
                    callbacks: {
                        label: function (tooltipItem, chart) {
                            var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
                            return datasetLabel + ': $' + number_format(tooltipItem.yLabel);
                        }
                    }
                }
            }
        });
    </script>
}